version: '3.3'
services:
    nginx:
      image: nginx:latest
      container_name: nginx
      restart: unless-stopped
      depends_on:
        - php
        - mysql
      ports:
        - "80:80"
        - "443:443"
        - "6003:6003"
      volumes:
        - ./www:/var/www/html
        - ./config/nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - ./ssl:/etc/nginx/ssl
        - /etc/localtime:/etc/localtime:ro
        - ./certbot/www/html:/var/www/html/certbot
      networks:
        - network01

    php:
      build: ./php
      container_name: php
      restart: unless-stopped
      volumes:
        - ./www:/var/www/html
        - /etc/localtime:/etc/localtime:ro
        - ./logs/php:/var/log/php
        - ./config/php-fpm/usersetting.ini:/usr/local/etc/php/conf.d/usersetting.ini
      expose:
        - "6003"
      entrypoint: ""
      command: bash -c "cron && exec docker-php-entrypoint php-fpm"
      networks:
        - network01

    mysql:
      image: mysql:latest
      container_name: mysql
      restart: unless-stopped
      volumes:
        - ./.data/db:/var/lib/mysql
        - ./logs/mysql:/var/log/mysql
        - ./config/mysql:/etc/mysql
      env_file: 
        - .env
      entrypoint: ""
      command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"
      networks:
        - network01

    certbot:
      image: certbot/certbot:latest
      volumes:
        - ./certbot/www/html:/var/www/certbot:rw
        - ./certbot/conf:/etc/letsencrypt:rw


    redis:
      image: 'bitnami/redis:latest'
      container_name: redis
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      networks:
        - network01

# networks
networks:
  network01:
    driver: bridge
